import type { LanguagePreset } from "../types/preset";

const GENERATED_BY = "# Ignore file generated by github.com/myntdeveloper/gitignore-generator";

export function buildGitignore(presets: LanguagePreset[]): string {
  const body = presets
    .map((preset) => preset.template.trim())
    .filter(Boolean)
    .join("\n\n")
    .trim();

  if (!body) {
    return GENERATED_BY;
  }

  return `${GENERATED_BY}\n\n${body}`.trimEnd();
}
